### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/conn/scheme/SchemeSocketFactory

### ISSUE THREAD

**Issue by nIvanovp** [bitbar/testdroid-samples#19]
Hello,

When I run your example (https://github.com/bitbar/testdroid-samples/tree/master/appium/sample-scripts/java)  I get an exception. I have to do something in my account before the run the tests?

Capabilities:Capabilities [{app=bn.ereader, testdroid_device=Asus Google Nexus 7 (2013) ME571KL, testdroid_testrun=TestRun 1, testdroid_username=n.ivanov@softteco.com, platformVersion=4.4, testdroid_target=Android, platformName=Android, deviceName=Android Phone,
 testdroid_project=BnEreader, app-package=bn.ereader, device=android, testdroid_app=384ca4f9-f8f5-478b-9947-bfe0bcfae83b/release.apk, app-activity=com.app.settings.SettingsActivity, testdroid_description=BnEreader international tests, te
stdroid_password=InterCore2}]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 48.348 sec <<< FAILURE!
bn.ereader.international.SampleAppiumTest  Time elapsed: 48.346 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/http/conn/scheme/SchemeSocketFactory
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:100)
        at org.openqa.selenium.remote.HttpCommandExecutor.<init>(HttpCommandExecutor.java:81)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
        at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:41)
        at bn.ereader.international.SampleAppiumTest.setUp(SampleAppiumTest.java:71)

bn.ereader.international.SampleAppiumTest  Time elapsed: 48.348 sec  <<< ERROR!
java.lang.NullPointerException: null
        at bn.ereader.international.SampleAppiumTest.tearDown(SampleAppiumTest.java:76)
Results :

Tests in error:
  SampleAppiumTest.setUp:71 ╗ NoClassDefFound org/apache/http/conn/scheme/Scheme...
  SampleAppiumTest.tearDown:76 NullPointer

-----------------------------------------------------------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project SampleAppiumJava: There are test failures.
[ERROR]
[ERROR] Please refer to D:\sf.n.ivanov\encore\international\BnEreaderI18n\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project SampleAppiumJava: There are test failures.

Please refer to D:\sf.n.ivanov\encore\international\BnEreaderI18n\target\surefire-reports for the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to D:\sf.n.ivanov\encore\international\BnEreaderI18n\target\surefire-reports for the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:82)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:169)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:733)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:631)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)

Thanks

**Comment by spedepekka** [comment]
Should be fixed now. Thanks to @itaiag
